### ISSUE TITLE
Minio replacement with S3

### ISSUE THREAD

**Issue by cakeinsauce** [epam/badgerdoc#21]
We should check if current project environment can work with S3 which will replace Minio. 
Check if:
- [x] Services can work with S3
  - [x] Minio Python SDK is compatible with S3
  - [x] Bucket URL replacement is enough for bootstrap
- [x] Services can connect to S3 k8s pod without credentials (internally)

**Comment by spiridonovfed** [comment]
Minio is fully compatible with AWS S3 - it's stated in Minio's documentation.

We've decided to crete environmental variable S3_BUCKET_PREFIX that will be used as prefix in bucket's name.

**Comment by spiridonovfed** [comment]
Authorization with having AWS_ACCESS_KEY_ID and AWS_ACCESS_KEY is possible:

1. aws configure --profile someprofilenamefors3 (and then provide all the credentials needed)
2. create env variable 'AWS_PROFILE_NAME' with value of someprofilenamefors3
3. start/restart assets app on uvicorn

the app itself will take all the credentials from aws config by using someprofilenamefors3 sent

**Comment by spiridonovfed** [comment]
Prefixes for buckets are not possible because buckets are top-level objects by design.
We could use prefixes for objects in buckets, but not for buckets itself.
Using minio.create_bucket() with prefixes is not possible. Using prefixes for objects requires some code rewrtitng - our 'buckets' will become actually 'folders'
