### ISSUE TITLE
Impossible to finish annotation task without any labels

### ISSUE THREAD

**Issue by DaryaGurtovenko** [epam/badgerdoc#228]
_Issue came from UAT_
Such cases are possible in real world.

**Preconditions:**
Job with at least one category of labels is created

**Steps:**
1. Open an annotation task.
2. Don’t annotate anything. Click “Finish labeling” button.

**Result:**
User is redirected to dashboard, an error message “Fields pages, validated, failed validation pages and categories are empty. Nothing to save." appears in the lower left corner
![image](https://user-images.githubusercontent.com/80756170/213179430-687e85f2-935b-484c-b6e7-d849a18eaa7c.png)

**Expected result:**
Finishing without any labels should be available.

**Comment by khyurri** [comment]
@MagicTearsAsunder 
Please, add some examples, where we can get regression

**Comment by MagicTearsAsunder** [comment]
> @MagicTearsAsunder Please, add some examples, where we can get regression

Possible issues:
General - pages_summary endpoint returns labeled pages as "not processed" because they are not considered as "annotated" OR the previous status before labeling instead of "annotated", which can affect several cases and more:

1. In the annotation task, set label, finish task. Go to the validation task and set page as invalid, save draft. Add label, save draft. Pages would be still considered as "invalid" because it does not recognized labeling as a new status.
2. In validation task, set page as valid, save draft. Then edit page and add a label. Pages would be still considered as "valid" (same reason).
3. After finishing "invalid" validation task, go to the newly created annotation task and add a label, save draft. Page status won't change.

**Comment by DaryaGurtovenko** [comment]
Retest on dev1 shown that we still have the start issue ('Impossible to finish annotation task without any labels' itself), and occurred error is the same - 'nothing to save'.

**Comment by DaryaGurtovenko** [comment]
Now finishing without any labeling is ready, but should be re-tested within  #227.
This one is closed as Verified.
