### ISSUE TITLE
Error on saving edited job

### ISSUE THREAD

**Issue by sbilevich** [epam/badgerdoc#304]
422 error when trying to save edited job on http://dev1.badgerdoc.com/api/v1/jobs/docs#/default/change_job_jobs__job_id__put

The issue lies in this end-point, it doesn't allow categories as objects:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/69203629/216911776-997f8219-b8f1-4e73-8a02-d233863867e7.png)

Body for request:
{
  "name": "test",
  "files": [
    872
  ],
  "datasets": [
  ],
  "is_draft": true,
  "is_auto_distribution": true,
  "annotators": [
    "02336646-f5d0-4670-b111-c140a3ad58b5", "45526cca-291a-405e-8234-6088454e18c4"
  ],
  "validators": [
  ],
  "owners": [
    "02336646-f5d0-4670-b111-c140a3ad58b5"
  ],
  "categories":[{"category_id": "taxonomy_testing_cat", "taxonomy_id": "taxonomy_1", "taxonomy_version": 1}],
  "validation_type": "cross"
}

**Comment by andrei-shulaev** [comment]
Discussed with @sbilevich. no changes needed. The issue was in the request parameter that was not expected. Files and dataset pram could be updated only if job is in pending status.

But during investigation was discovered, pure coverage with logging in module responsible for annotation service communication. This issue should be fixed later according to priority.
