### ISSUE TITLE
No categories for extensive coverage for annotator

### ISSUE THREAD

**Issue by sbilevich** [epam/badgerdoc#637]
Add an extensive coverage job with some categories;
![image](https://github.com/epam/badgerdoc/assets/69203629/0fc9f836-2515-4fc6-ba2c-45ae51f2e581)
![image](https://github.com/epam/badgerdoc/assets/69203629/6e33b7bb-a0b4-4dd5-87e1-fbfde0ede268)
Login as annotator and go to task by this job: There are no categories in the list
![image](https://github.com/epam/badgerdoc/assets/69203629/348cd0e9-12fe-4f4d-8147-50492b66d2a4)
![image](https://github.com/epam/badgerdoc/assets/69203629/56fff482-9d61-43af-b479-e6280056362a)
![image](https://github.com/epam/badgerdoc/assets/69203629/5791619d-90fa-4c6e-990c-f4e82703eebc)

**Comment by Iogsotot** [comment]
pls specify examples, I can't reproduce
![image](https://github.com/epam/badgerdoc/assets/50149163/61ffb09b-13ce-4419-bfb2-a6b7764f3874)
![image](https://github.com/epam/badgerdoc/assets/50149163/8e6e79e0-6ca6-4897-bbc2-8154c65caade)

**Comment by sbilevich** [comment]
http://dev1.badgerdoc.com/annotation/tasks/5576
creds: annotator/annotator

**Comment by Iogsotot** [comment]
Thanks, Svetlana!

In this example, the categories are not displayed even for the `admin` role. 
Unfortunately, it was not possible to reproduce the issue on other extractions(cross, ext cov with categories), the bug is visible only on the specified example. Investigation needed

**Comment by Tokhirov-Abzal** [comment]
The bug was related to type of selected categories. If user selected categories with just one type 'Link', then categories will not appear while annotation. So the only way to fix it is when user selects category with type 'Link', he should select category with type 'Box' as well while adding new Job.

![image](https://github.com/epam/badgerdoc/assets/67236305/06329995-8d1c-4a88-b496-66971514ab3c)

**Comment by MarinaVorobeva21** [comment]
Fixed (inline message is displayed for Link categories)
